### ISSUE TITLE
Remember cookie choice for whole website

### ISSUE THREAD

**Issue by martinbaerwolff** [OpenTrafficCam/documentation#37]
After accepting cookies, they are asked again for every sub page of the website as well as after refreshing. I suppose this is not how it is meant to be?

**Comment by frunika** [comment]
It's currently a bug in the plugin and already know there. The developer promised a fix.

**Comment by frunika** [comment]
#38

**Comment by frunika** [comment]
I switched to a new plugin, using the same javascripts, but seems to save the cookie. New plugin is [Cookie Consent](https://github.com/naucon/grav-plugin-cookieconsent)
