### ISSUE TITLE
Gui tool used

### ISSUE THREAD

**Issue by martinbaerwolff** [OpenTrafficCam/documentation#8]
Add the gui tool used in OpenTrafficCam to the coding section of documentation

**Comment by frunika** [comment]
I don't understand it fully. Should we add some information, that we currently decided to use PySimpleGUI?

**Comment by martinbaerwolff** [comment]
Yes, that is what I meant. Do you think it would help or should we not document this since it is maybe just tempory?

**Comment by frunika** [comment]
Why not? It says what we have decided to do. There is usually a discussion behind something like that.

**Comment by martinbaerwolff** [comment]
Yes, why not. And also it is nice for Mike of PysimplGUI ;) Should I add the following section to the stage version of the docs?: 

For now we decided on using [PysimpleGUI](https://github.com/PySimpleGUI/PySimpleGUI) to build the OpenTrafficCam user interface, as it is lightweight and easy to start with. Whenever possible, we try to separate the gui code from all other code. All the gui modules have a place in the "gui" subpackage of the respective OT repository:

- [OTCamera/otcamera/gui](https://github.com/OpenTrafficCam/OTCamera/tree/master/otcamera/gui)
- [OTVision/otvision/gui](https://github.com/OpenTrafficCam/OTvision/tree/master/otvision/gui)
- [OTAnalytics/otanalytics/gui](https://github.com/OpenTrafficCam/OTAnalytics/tree/master/otanalytics/gui)

In the future we can also imagine using a web framework for user interaction. This would also help to enable remote access to local GPU machines or high performance computing centers.

**Comment by martinbaerwolff** [comment]
Pasting the links I recognized we capitalized OTVision/OTVision and OTAnalytics/OTAnalytics but we did not capitalize OTCamera/otcamera

**Comment by frunika** [comment]
sounds good, go for it

**Comment by martinbaerwolff** [comment]
Published on stage.opentrafficcam.org
